### ISSUE TITLE
Unable to create QueryDB

### ISSUE THREAD

**Issue by almutwerner** [soedinglab/spacepharer#5]
## Context
Hey there!
I tried to create the QueryDB in three different ways, none of it worked. Creating the TargetDB did work though. Preferably, I would like to be able to use my own Spacers. I do have full permission on all folders and enough space.

## Steps to Reproduce (for bugs)
A) spacepharer parsespacer ./MinCED/*.crisprs queryDB 
Before to create the files:
for x in *.fna; do \
/work_beegfs/sunam157/minced/minced $x /work_dagan/sunam157/OMZ/SpacePHARER/MinCED/$x.crisprs /work_dagan/sunam157/OMZ/SpacePHARER/MinCED/$x.gff ;done 

B) spacepharer downloaddb spacers_dion_et_al_2021 querySetDB tmpFolder

C) spacepharer downloaddb spacers_shmakov_et_al_2017 querySetDB tmpFolder_queryDB

## Spacepharer Output (for bugs)
A)
run_SpacePHARER.sh: line 15: 13717 Segmentation fault      spacepharer parsespacer ./MinCED/*.crisprs queryDB

B)
Selected database spacers_dion_et_al_2021 was not found

C)
2021-04-16 11:27:37 URL:http://wwwuser.gwdg.de/~compbiol/spacepharer/2018_09/spacers_shmakov_et_al_2017.tar.gz [15891003/15891003] -> "spacers_shmakov_et_al_2017.tar.gz" [1]
2021-04-16 11:27:38 URL:http://wwwuser.gwdg.de/~compbiol/spacepharer/2018_09/spacers_shmakov_et_al_2017.tsv [691088/691088] -> "spacers_shmakov_et_al_2017.tsv" [1]
tmpFolder_queryDB/3704848674854149300/downloadb.sh: line 121: /work_dagan/sunam157/OMZ/SpacePHARER/spacepharer: No such file or directory
Error: tar2db failed

(if I manually create the not found directory, it doesn't work either.)

## Your Environment
Version: 4.228b9e5 (via Conda)

**Comment by RuoshiZhang** [comment]
I fixed the bug in `parsespacer` when parsing CRT/MINCED format in c51a543b5f9acc4daf30ee0462f012dd77856f12. Can you update to the latest version of spacepharer (either compile from source or download from https://mmseqs.com/spacepharer/)?
Regarding spacers_dion_et_al_2021 dataset, it is added after the release. It will also be available when you update to the latest git version.

**Comment by almutwerner** [comment]
Thank you for your reply! I reinstalled from source to version c51a543b5f9acc4daf30ee0462f012dd77856f12, but still get the error:
run_SpacePHARER.sh: line 17: 11499 Segmentation fault      spacepharer parsespacer ./MinCED/*.crisprs queryDB

**Comment by milot-mirdita** [comment]
Could you please upload one of the minced output files so we can try to reproduce the issue locally?

**Comment by almutwerner** [comment]
While looking for a MinCED outputfile to give you, I saw some of them were empty. I removed all empty ones and ran it again, and it worked like a charm, all the way through!  Sorry about that, I should have thought about it earlier. Thank you for your help!

**Comment by milot-mirdita** [comment]
That’s very helpful! That is still a bug on our side that we can fix.

**Comment by milot-mirdita** [comment]
Are these files actually 0-byte large? If they are != 0, could you still upload one?
It seems like we should be handling this case correctly.

**Comment by almutwerner** [comment]
I removed the files with 
find . -size  0 -print -delete
so actually 0 bytes large. I will attach one anyways

[3300030749.fna.zip](https://github.com/soedinglab/spacepharer/files/6343769/3300030749.fna.zip)

**Comment by milot-mirdita** [comment]
Thanks a lot! You found an issue in the MMseqs2 framework that SpacePHARER uses that was introduced about 4 years ago :D. We'll fix the problem in MMseqs2 and update SpacePHARER asap.

**Comment by milot-mirdita** [comment]
The issue should now be fixed in the latest release.
